alias c='clear'
alias wm='workmux'
alias ls='ls --color=auto'
alias ssh='TERM=xterm-256color ssh'

alias tf='terraform'
alias tfin='terraform init'
alias tfp='terraform plan'
alias tfa='terraform apply'
alias tff='terraform fmt'

alias g='git'
alias gst='git status'
alias ga='git add'
alias gaa='git add --all'
alias gc='git commit'
alias gcm='git commit -m'
alias gca='git commit --amend'
alias gcan='git commit --amend --no-edit'
alias gd='git diff'
alias gds='git diff --staged'
alias gs='git switch'
alias gsc='git switch -c'
alias gb='git branch'
alias gf='git fetch'
alias gp='git pull'
alias gpu='git push'
alias gpf='git push --force-with-lease'
alias grb='git rebase'
alias grs='git restore'
alias grss='git restore --staged'
alias gsta='git stash'
alias gstp='git stash pop'
alias glog='git log --oneline --graph --decorate'
