require "config.config"
require "config.keyboard"
require "config.mouse"
require "config.layout"
require "config.menu"
require "config.rules"
require "config.wallpaper"
-- require "config.titlebar"
require "config.desktop_decoration"
require "config.notifications"
