general {
    hide_cursor = true
}

animations {
    enabled = false
}

background {
    monitor =
}

input-field {
    monitor =
    size = 300, 50
    fade_on_empty = false
    fail_text = $PAMFAIL
}

label {
    monitor =
    text = $TIME
    font_size = 64
    position = 0, 120
}
