vim.g.mapleader = " "

vim.o.guicursor = "a:block"
vim.o.number = true
vim.o.relativenumber = true
vim.o.tabstop = 4
vim.o.softtabstop = 4
vim.o.shiftwidth = 4
vim.o.expandtab = true
vim.o.wrap = false
vim.o.swapfile = false
vim.o.undofile = true
vim.o.hlsearch = false
vim.o.colorcolumn = "80"
vim.o.cursorline = true
vim.o.updatetime = 250
vim.o.scrolloff = 8
vim.o.signcolumn = "yes"
vim.o.winborder = "rounded"
