[arch]
packages = [
    "go",
    { name = "rustup", hooks = { after_install = ["rustup", "default", "stable"] } },
    "terraform",
]

[mise]
packages = [
    { name = "node", options = { version = "lts" } },
    { name = "pnpm", options = { version = "latest" } },
]
